server:
    port: 18090
spring:
    application:
        name: order
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.56.104:3306/changgou_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root
    redis:
        host: 192.168.56.104
        port: 6379
    main:
        allow-bean-definition-overriding: true
    rabbitmq:
        host: 192.168.56.104
        port: 5672
        username: guest
        password: guest

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka
    instance:
        prefer-ip-address: true
feign:
    hystrix:
        enabled: true
#hystrix 配置
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
                    #信号量隔离  此时不会开启新线程
                    strategy: SEMAPHORE

#位置支付交换机和队列
mq:
    pay:
        exchange:
            order: exchange.order
        queue:
            order: queue.order
        routing:
            key: queue.order